// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// combinpmatr_impl
NumericMatrix combinpmatr_impl(NumericMatrix X, Nullable<NumericVector> Wk);
RcppExport SEXP _ConsRank_combinpmatr_impl(SEXP XSEXP, SEXP WkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type Wk(WkSEXP);
    rcpp_result_gen = Rcpp::wrap(combinpmatr_impl(X, Wk));
    return rcpp_result_gen;
END_RCPP
}
// findbranches_impl
NumericMatrix findbranches_impl(NumericMatrix R, IntegerVector ord, IntegerVector b, bool FULL);
RcppExport SEXP _ConsRank_findbranches_impl(SEXP RSEXP, SEXP ordSEXP, SEXP bSEXP, SEXP FULLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type R(RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type FULL(FULLSEXP);
    rcpp_result_gen = Rcpp::wrap(findbranches_impl(R, ord, b, FULL));
    return rcpp_result_gen;
END_RCPP
}
// kemenydesign_cpp
NumericMatrix kemenydesign_cpp(NumericMatrix X);
RcppExport SEXP _ConsRank_kemenydesign_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(kemenydesign_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// kemenydesign_impl
NumericMatrix kemenydesign_impl(NumericMatrix X);
RcppExport SEXP _ConsRank_kemenydesign_impl(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(kemenydesign_impl(X));
    return rcpp_result_gen;
END_RCPP
}
// PenaltyBB2_batch_impl
NumericVector PenaltyBB2_batch_impl(NumericMatrix cij, NumericMatrix candidates, IntegerVector ord);
RcppExport SEXP _ConsRank_PenaltyBB2_batch_impl(SEXP cijSEXP, SEXP candidatesSEXP, SEXP ordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cij(cijSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ord(ordSEXP);
    rcpp_result_gen = Rcpp::wrap(PenaltyBB2_batch_impl(cij, candidates, ord));
    return rcpp_result_gen;
END_RCPP
}
// PenaltyBB2_impl
double PenaltyBB2_impl(NumericMatrix cij, NumericVector candidate, IntegerVector ord);
RcppExport SEXP _ConsRank_PenaltyBB2_impl(SEXP cijSEXP, SEXP candidateSEXP, SEXP ordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cij(cijSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type candidate(candidateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ord(ordSEXP);
    rcpp_result_gen = Rcpp::wrap(PenaltyBB2_impl(cij, candidate, ord));
    return rcpp_result_gen;
END_RCPP
}
// scorematrix_impl
NumericMatrix scorematrix_impl(NumericVector x);
RcppExport SEXP _ConsRank_scorematrix_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(scorematrix_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// ReorderingBB_impl
NumericVector ReorderingBB_impl(NumericVector RR);
RcppExport SEXP _ConsRank_ReorderingBB_impl(SEXP RRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type RR(RRSEXP);
    rcpp_result_gen = Rcpp::wrap(ReorderingBB_impl(RR));
    return rcpp_result_gen;
END_RCPP
}
// scorematrix_cpp
NumericMatrix scorematrix_cpp(SEXP X);
RcppExport SEXP _ConsRank_scorematrix_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(scorematrix_cpp(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ConsRank_combinpmatr_impl", (DL_FUNC) &_ConsRank_combinpmatr_impl, 2},
    {"_ConsRank_findbranches_impl", (DL_FUNC) &_ConsRank_findbranches_impl, 4},
    {"_ConsRank_kemenydesign_cpp", (DL_FUNC) &_ConsRank_kemenydesign_cpp, 1},
    {"_ConsRank_kemenydesign_impl", (DL_FUNC) &_ConsRank_kemenydesign_impl, 1},
    {"_ConsRank_PenaltyBB2_batch_impl", (DL_FUNC) &_ConsRank_PenaltyBB2_batch_impl, 3},
    {"_ConsRank_PenaltyBB2_impl", (DL_FUNC) &_ConsRank_PenaltyBB2_impl, 3},
    {"_ConsRank_scorematrix_impl", (DL_FUNC) &_ConsRank_scorematrix_impl, 1},
    {"_ConsRank_ReorderingBB_impl", (DL_FUNC) &_ConsRank_ReorderingBB_impl, 1},
    {"_ConsRank_scorematrix_cpp", (DL_FUNC) &_ConsRank_scorematrix_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ConsRank(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
