# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
combinpmatr_impl <- function(X, Wk = NULL) {
    .Call(`_ConsRank_combinpmatr_impl`, X, Wk)
}

#' @noRd
findbranches_impl <- function(R, ord, b, FULL) {
    .Call(`_ConsRank_findbranches_impl`, R, ord, b, FULL)
}

#' @noRd
kemenydesign_cpp <- function(X) {
    .Call(`_ConsRank_kemenydesign_cpp`, X)
}

#' @noRd
kemenydesign_impl <- function(X) {
    .Call(`_ConsRank_kemenydesign_impl`, X)
}

PenaltyBB2_batch_impl <- function(cij, candidates, ord) {
    .Call(`_ConsRank_PenaltyBB2_batch_impl`, cij, candidates, ord)
}

PenaltyBB2_impl <- function(cij, candidate, ord) {
    .Call(`_ConsRank_PenaltyBB2_impl`, cij, candidate, ord)
}

scorematrix_impl <- function(x) {
    .Call(`_ConsRank_scorematrix_impl`, x)
}

ReorderingBB_impl <- function(RR) {
    .Call(`_ConsRank_ReorderingBB_impl`, RR)
}

scorematrix_cpp <- function(X) {
    .Call(`_ConsRank_scorematrix_cpp`, X)
}

